### ISSUE TITLE
doesn't convert "inner" prop when using snabbdom-to-html

### ISSUE THREAD

**Issue by klaaz0r** [krainboltgreene/snabbdom-helpers#6]
When using the helpers with snabbdoms to html it seems that the inner property does not get rendered, selectors do work fine.
```javascript
import toHTML from 'snabbdom-to-html'
import { article } from 'snabbdom-helpers'

const node = article({
  selector: '.works',
  inner: 'doesnt work'
})

const html = toHTML(node)

console.log(html) // -> <article class="works"></article>
```

**Comment by krainboltgreene** [comment]
Oh that's so weird. Okay, I'll see about fixing this asap.

**Comment by alexis-de-la-torre** [comment]
You fixed it on 9f684d4c2a66493881830b5ade01853083643734 but maybe forgot to update the npm package.
@klaaz0r  you are using 'inner' because you are following the readme but the npm package is still specting 'content'

**Comment by krainboltgreene** [comment]
Argh yes, will release.

**Comment by krainboltgreene** [comment]
Fixed :D
